name: Build debian

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get build dependencies
        run: |
          sudo apt-add-repository ppa:slaclau/ppa-pre
          sudo apt update
          sudo apt install devscripts equivs
          sudo mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
      - name: Import key
        run: |
          GPG_KEY_ID=$(echo "${{ secrets.PPA_GPG_PRIVATE_KEY }}" | gpg --import-options show-only --import | sed -n '2s/^\s*//p')
          echo $GPG_KEY_ID
          echo "${{ secrets.PPA_GPG_PRIVATE_KEY }}" | gpg --batch --import
      - name: Build
        run: |
          dpkg-buildpackage -S -sa
          dpkg-buildpackage -b
          mv ../python-lib-detect-testenv_*.* .
      - name: Upload debian package
        uses: actions/upload-artifact@v3
        with:
          name: Debian
          path: |
            python-lib-detect-testenv*.deb
            python-lib-detect-testenv*.dsc
            python-lib-detect-testenv*.tar.xz
            python-lib-detect-testenv*.changes
      - name: Publish package to prerelease PPA
        run: |
          sudo apt install dput
          dput ppa:slaclau/ppa-pre python-lib-detect-testenv*source.changes
        if: github.ref == 'refs/heads/master'